---
name: Flowable
description: Business Process Engines
url: http://www.flowable.org
baseurl: ""
permalink: "/blog/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
paginate: 5
timezone: Europe/Amsterdam
highlighter: rouge
repository: Flowable/flowable
defaults:
- scope:
    path: docs
    type: pages
  values:
    layout: docs
    sectionid: docs
- scope:
    path: tips
    type: pages
  values:
    sectionid: docs
- scope:
    path: contributing
    type: pages
  values:
    sectionid: docs
- scope:
    path: team
    type: pages
  values:
    sectionid: team
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
markdown: kramdown
# redcarpet:
#   extensions:
#   - fenced_code_blocks
#   - footnotes
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  style: :compressed
  sass_dir: _css
gems:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
flowable_version: 6.4.2
flowable_5_version: 5.23.0
